### ISSUE TITLE
Heroku seems does not support [user-env-compile] anymore, is it?

### ISSUE THREAD

**Issue by VitoVan** [jsmpereira/heroku-buildpack-cl#6]
try: http://devcenter.heroku.com/articles/labs-user-env-compile ,it just redirected.
and, when try "heroku labs:enable user-env-compile -a project", it returns:
 !    No such feature: user-env-compile

**Comment by jsmpereira** [comment]
Hi @VitoVan.

The ```user-env-compile``` feature has been deprecated. More information on how to go about it at https://devcenter.heroku.com/changelog-items/416.

**Comment by jsmpereira** [comment]
Also, may I suggest looking into https://github.com/avodonosov/heroku-buildpack-cl2 which is a cleaner approach on the CL buildpack :)

**Comment by VitoVan** [comment]
thanks, it works.
